# Generated by Django 5.0.6 on 2024-05-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_note_delete_memory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="description",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
